// Generated by gencpp from file light_robot/textmessageRequest.msg
// DO NOT EDIT!


#ifndef LIGHT_ROBOT_MESSAGE_TEXTMESSAGEREQUEST_H
#define LIGHT_ROBOT_MESSAGE_TEXTMESSAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace light_robot
{
template <class ContainerAllocator>
struct textmessageRequest_
{
  typedef textmessageRequest_<ContainerAllocator> Type;

  textmessageRequest_()
    : mystring()  {
    }
  textmessageRequest_(const ContainerAllocator& _alloc)
    : mystring(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mystring_type;
  _mystring_type mystring;





  typedef boost::shared_ptr< ::light_robot::textmessageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::light_robot::textmessageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct textmessageRequest_

typedef ::light_robot::textmessageRequest_<std::allocator<void> > textmessageRequest;

typedef boost::shared_ptr< ::light_robot::textmessageRequest > textmessageRequestPtr;
typedef boost::shared_ptr< ::light_robot::textmessageRequest const> textmessageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::light_robot::textmessageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::light_robot::textmessageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::light_robot::textmessageRequest_<ContainerAllocator1> & lhs, const ::light_robot::textmessageRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mystring == rhs.mystring;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::light_robot::textmessageRequest_<ContainerAllocator1> & lhs, const ::light_robot::textmessageRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace light_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::textmessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::textmessageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::textmessageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::textmessageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::textmessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::textmessageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::light_robot::textmessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8054fff057e825e73968032a7c26bc8";
  }

  static const char* value(const ::light_robot::textmessageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8054fff057e825eULL;
  static const uint64_t static_value2 = 0x73968032a7c26bc8ULL;
};

template<class ContainerAllocator>
struct DataType< ::light_robot::textmessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "light_robot/textmessageRequest";
  }

  static const char* value(const ::light_robot::textmessageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::light_robot::textmessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mystring\n"
"\n"
;
  }

  static const char* value(const ::light_robot::textmessageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::light_robot::textmessageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mystring);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct textmessageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::light_robot::textmessageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::light_robot::textmessageRequest_<ContainerAllocator>& v)
  {
    s << indent << "mystring: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mystring);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHT_ROBOT_MESSAGE_TEXTMESSAGEREQUEST_H
