// Generated by gencpp from file light_robot/textmessageResponse.msg
// DO NOT EDIT!


#ifndef LIGHT_ROBOT_MESSAGE_TEXTMESSAGERESPONSE_H
#define LIGHT_ROBOT_MESSAGE_TEXTMESSAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace light_robot
{
template <class ContainerAllocator>
struct textmessageResponse_
{
  typedef textmessageResponse_<ContainerAllocator> Type;

  textmessageResponse_()
    : count(0)  {
    }
  textmessageResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::light_robot::textmessageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::light_robot::textmessageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct textmessageResponse_

typedef ::light_robot::textmessageResponse_<std::allocator<void> > textmessageResponse;

typedef boost::shared_ptr< ::light_robot::textmessageResponse > textmessageResponsePtr;
typedef boost::shared_ptr< ::light_robot::textmessageResponse const> textmessageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::light_robot::textmessageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::light_robot::textmessageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::light_robot::textmessageResponse_<ContainerAllocator1> & lhs, const ::light_robot::textmessageResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::light_robot::textmessageResponse_<ContainerAllocator1> & lhs, const ::light_robot::textmessageResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace light_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::textmessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::textmessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::textmessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::textmessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::textmessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::textmessageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::light_robot::textmessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602d642babe509c7c59f497c23e716a9";
  }

  static const char* value(const ::light_robot::textmessageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602d642babe509c7ULL;
  static const uint64_t static_value2 = 0xc59f497c23e716a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::light_robot::textmessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "light_robot/textmessageResponse";
  }

  static const char* value(const ::light_robot::textmessageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::light_robot::textmessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 count\n"
"\n"
;
  }

  static const char* value(const ::light_robot::textmessageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::light_robot::textmessageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct textmessageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::light_robot::textmessageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::light_robot::textmessageResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHT_ROBOT_MESSAGE_TEXTMESSAGERESPONSE_H
